/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.js' */
"use strict";

module.exports = {
    plugins: ["nkgrnkgr-react"],
    rules: {
        "nkgrnkgr-react/enable-only-default-import-react": 2
    }
};
